# Generated by Django 4.1.7 on 2023-04-09 21:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_alter_contactus_created_alter_rate_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 9, 21, 54, 59, 215567, tzinfo=datetime.timezone.utc)),
        ),
    ]
