# Generated by Django 4.1.7 on 2023-03-12 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_alter_rate_currency_alter_source_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='email_from',
            new_name='email',
        ),
        migrations.AddField(
            model_name='contactus',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 12, 18, 11, 50, 699693, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='contactus',
            name='name',
            field=models.CharField(default=0, max_length=128),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='subject',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='rate',
            name='currency',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Dollar'), (2, 'Euro')], default=1),
        ),
    ]
