# Generated by Django 4.1.7 on 2023-03-17 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0007_requestresponselog_alter_contactus_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 17, 18, 55, 45, 883250, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='requestresponselog',
            name='request_method',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='requestresponselog',
            name='time',
            field=models.IntegerField(),
        ),
    ]
