# Generated by Django 4.1.7 on 2023-03-27 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0008_alter_contactus_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 27, 14, 57, 7, 414753, tzinfo=datetime.timezone.utc)),
        ),
    ]
