# Generated by Django 4.1.7 on 2023-03-30 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0009_alter_contactus_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 30, 19, 24, 50, 939294, tzinfo=datetime.timezone.utc)),
        ),
    ]
